export const apiConstants = {
    baseUrl: process.env.NODE_ENV === 'production' ? 'https://temonetback.test/api' : 'https://temonetback.test/api',
}

export const authConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',
    LOGOUT: 'USERS_LOGOUT',
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    VERIFY_REQUEST: 'USERS_VERIFY_REQUEST',
    VERIFY_SUCCESS: 'USERS_VERIFY_SUCCESS',
    VERIFY_FAILURE: 'USERS_VERIFY_FAILURE',
    SET_ERROR_MSG:'SET_ERROR_MSG',
    SET_DEFAULT_ADDRESS: 'SET_DEFAULT_ADDRESS',
};


export const therapyConstant = {
    STORE_REQUEST:"THERAPY_STORE_REQUEST",
    STORE_SUCCESS:"THERAPY_STORE_SUCCESS",
    STORE_FAILURE:"THERAPY_STORE_FAILURE",
    INDEX_REQUEST:"THERAPY_INDEX_REQUEST",
    INDEX_FAILURE:"THERAPY_INDEX_FAILURE",
}

export const alertConstants = {
    FULLPAGE_LOADER: 'FULLPAGE_LOADER',
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',
    LOGOUT: 'USERS_LOGOUT',
};
